Repository itera-io/terraform-provider-taikun, pull requests merged in 2021-12, with the labels that each got.

#164 chore(sweepers): schedule to run 3h later
  .github/workflows/sweep.yml
Labels: sweeper

#165 chore(sweepers): schedule to run 3h later
  .github/workflows/sweep.yml
Labels: sweeper

#169 fix(project): use renamed k8s profile list method
  go.mod
  go.sum
  taikun/resource_taikun_project.go
Labels: bug, build

#170 fix(organization): use correct id in datasource
  docs/data-sources/organization.md
  taikun/data_source_taikun_organization.go
  taikun/data_source_taikun_organization_test.go
  templates/data-sources/organization.md.tmpl
Labels: bug

#174 fix(projects): fix quota unit
  taikun/resource_taikun_project.go
Labels: bug

#173 ci: improvements
  .github/workflows/sweep.yml
  .github/workflows/test.yml
Labels: ci

#176 fix(cloud_credential_aws): update create endpoint parameters
  go.mod
  go.sum
  taikun/helper.go
  taikun/resource_taikun_cloud_credential_aws.go
Labels: bug
