Repository itera-io/terraform-provider-taikun, pull requests merged in 2021-11, with the labels that each got.

#132 refactor: remove useless attributes
  docs/data-sources/access_profile.md
  docs/data-sources/access_profiles.md
  docs/resources/access_profile.md
  docs/resources/organization.md
  go.mod
  go.sum
  taikun/data_source_taikun_access_profiles_test.go
  taikun/data_source_taikun_organization.go
  taikun/data_source_taikun_organizations.go
  taikun/data_source_taikun_users_test.go
  taikun/resource_taikun_access_profile.go
  taikun/resource_taikun_organization.go
Labels: refactor

#133 fix(alerting_profile): set emails computed to true
  taikun/resource_taikun_alerting_profile.go
Labels: bug, refactor

#136 ci(test): change concurrency scope and triggers
  .github/workflows/test.yml
Labels: ci

#137 refactor(project): no wait for ready status on delete if empty
  taikun/resource_taikun_project.go
Labels: refactor

#140 refactor(projects): only wait in create if project isn't empty
  taikun/resource_taikun_project.go
Labels: refactor

#139 fix(project): add validation if lb is taikun
  taikun/helper.go
  taikun/resource_taikun_project.go
Labels: bug

#130 docs: proofread
  docs/resources/alerting_profile.md
  docs/resources/slack_configuration.md
  examples/resources/taikun_alerting_profile/resource.tf
  examples/resources/taikun_slack_configuration/resource.tf
Labels: documentation

#138 feat: add backup policies
  docs/resources/backup_policy.md
  examples/resources/taikun_backup_policy/resource.tf
  go.mod
  go.sum
  taikun/helper.go
  taikun/provider.go
  taikun/resource_taikun_backup_policy.go
  taikun/resource_taikun_project_test.go
  templates/resources/backup_policy.md.tmpl
Labels: feat

#142 test: retry read in check destroy
  .github/workflows/test.yml
  taikun/data_source_taikun_access_profiles_test.go
  taikun/data_source_taikun_alerting_profiles_test.go
  taikun/data_source_taikun_backup_credentials_test.go
  taikun/data_source_taikun_billing_credentials_test.go
  taikun/data_source_taikun_billing_rules_test.go
  taikun/data_source_taikun_cloud_credentials_aws_test.go
  taikun/data_source_taikun_cloud_credentials_azure_test.go
  taikun/data_source_taikun_cloud_credentials_openstack_test.go
  taikun/data_source_taikun_flavors_test.go
  taikun/data_source_taikun_kubernetes_profiles_test.go
  taikun/data_source_taikun_organization_test.go
  taikun/data_source_taikun_organizations_test.go
  taikun/data_source_taikun_projects_test.go
  taikun/data_source_taikun_showback_credentials_test.go
  taikun/data_source_taikun_showback_rules_test.go
  taikun/data_source_taikun_slack_configurations_test.go
  taikun/data_source_taikun_users.go
  taikun/data_source_taikun_users_test.go
  taikun/resource_taikun_access_profile.go
  taikun/resource_taikun_access_profile_test.go
  taikun/resource_taikun_alerting_profile_test.go
  taikun/resource_taikun_backup_credential_test.go
  taikun/resource_taikun_billing_credential_test.go
  taikun/resource_taikun_billing_rule_test.go
  taikun/resource_taikun_cloud_credential_aws_test.go
  taikun/resource_taikun_cloud_credential_azure_test.go
  taikun/resource_taikun_cloud_credential_openstack_test.go
  taikun/resource_taikun_kubernetes_profile_test.go
  taikun/resource_taikun_organization_billing_rule_attachment_test.go
  taikun/resource_taikun_organization_test.go
  taikun/resource_taikun_project.go
  taikun/resource_taikun_project_test.go
  taikun/resource_taikun_project_user_attachment_test.go
  taikun/resource_taikun_showback_credential_test.go
  taikun/resource_taikun_showback_rule_test.go
  taikun/resource_taikun_slack_configuration_test.go
  taikun/resource_taikun_user_test.go
Labels: test

#144 feat(project): get default kubernetes and access profile if not specified
  docs/data-sources/project.md
  docs/resources/project.md
  taikun/resource_taikun_project.go
Labels: feat

#145 chore(goreleaser): generate changelog
  .goreleaser.yml
  CHANGELOG.md
Labels: ci

#148 ci: add linter
  .github/workflows/test.yml
  go.mod
  go.sum
  taikun/data_source_taikun_user.go
  taikun/helper.go
  taikun/resource_taikun_backup_policy.go
  taikun/schema_helpers.go
Labels: ci

#146 refactor: unlock before updating resources
  taikun/resource_taikun_access_profile.go
  taikun/resource_taikun_alerting_profile.go
  taikun/resource_taikun_backup_credential.go
  taikun/resource_taikun_billing_credential.go
  taikun/resource_taikun_cloud_credential_aws.go
  taikun/resource_taikun_cloud_credential_azure.go
  taikun/resource_taikun_cloud_credential_openstack.go
  taikun/resource_taikun_kubernetes_profile.go
  taikun/resource_taikun_organization.go
  taikun/resource_taikun_project.go
  taikun/resource_taikun_showback_credential.go
  taikun/resource_taikun_slack_configuration.go
Labels: refactor

#147 refactor: split generate read into two functions instead of setting bool flag
  taikun/data_source_taikun_access_profile.go
  taikun/data_source_taikun_alerting_profile.go
  taikun/data_source_taikun_backup_credential.go
  taikun/data_source_taikun_billing_credential.go
  taikun/data_source_taikun_billing_rule.go
  taikun/data_source_taikun_cloud_credential_aws.go
  taikun/data_source_taikun_cloud_credential_azure.go
  taikun/data_source_taikun_cloud_credential_openstack.go
  taikun/data_source_taikun_kubeconfig.go
  taikun/data_source_taikun_kubernetes_profile.go
  taikun/data_source_taikun_project.go
  taikun/data_source_taikun_showback_credential.go
  taikun/data_source_taikun_showback_rule.go
  taikun/data_source_taikun_slack_configuration.go
  taikun/data_source_taikun_user.go
  taikun/resource_taikun_access_profile.go
  taikun/resource_taikun_alerting_profile.go
  taikun/resource_taikun_backup_credential.go
  taikun/resource_taikun_backup_policy.go
  taikun/resource_taikun_billing_credential.go
  taikun/resource_taikun_billing_rule.go
  taikun/resource_taikun_cloud_credential_aws.go
  taikun/resource_taikun_cloud_credential_azure.go
  taikun/resource_taikun_cloud_credential_openstack.go
  taikun/resource_taikun_kubeconfig.go
  taikun/resource_taikun_kubernetes_profile.go
  taikun/resource_taikun_organization.go
  taikun/resource_taikun_organization_billing_rule_attachment.go
  taikun/resource_taikun_project.go
  taikun/resource_taikun_project_user_attachment.go
  taikun/resource_taikun_showback_credential.go
  taikun/resource_taikun_showback_rule.go
  taikun/resource_taikun_slack_configuration.go
  taikun/resource_taikun_user.go
Labels: refactor

#149 feat(users): remove useless fields
  docs/data-sources/user.md
  docs/data-sources/users.md
  docs/resources/user.md
  taikun/data_source_taikun_users_test.go
  taikun/resource_taikun_user.go
  taikun/resource_taikun_user_test.go
Labels: feat

#151 ci(test): add dev branch trigger
  .github/workflows/test.yml
Labels: ci

#150 refactor: remove default from api_host attribute from provider configuration
  docs/index.md
  scripts/update_client_dependency.sh
  taikun/provider.go
  taikun/provider_test.go
Labels: refactor, build

#152 feat(organizations): add default value for discount_rate
  docs/resources/organization.md
  taikun/resource_taikun_organization.go
Labels: feat

#158 feat: do not use client api host
  taikun/provider.go
Labels: feat

#159 ci(release): fix action version
  .github/workflows/release.yml
Labels: ci

#143 feat: add policy_profile
  docs/data-sources/policy_profile.md
  docs/data-sources/policy_profiles.md
  docs/data-sources/project.md
  docs/data-sources/projects.md
  docs/resources/policy_profile.md
  docs/resources/project.md
  examples/data-sources/taikun_policy_profile/data-source.tf
  examples/data-sources/taikun_policy_profiles/data-source.tf
  examples/resources/taikun_policy_profile/import.sh
  examples/resources/taikun_policy_profile/resource.tf
  examples/resources/taikun_project/resource.tf
  taikun/data_source_taikun_alerting_profiles.go
  taikun/data_source_taikun_kubernetes_profile_test.go
  taikun/data_source_taikun_policy_profile.go
  taikun/data_source_taikun_policy_profile_test.go
  taikun/data_source_taikun_policy_profiles.go
  taikun/data_source_taikun_policy_profiles_test.go
  taikun/data_source_taikun_projects.go
  taikun/helper.go
  taikun/provider.go
  taikun/resource_taikun_backup_policy.go
  taikun/resource_taikun_cloud_credential_aws.go
  taikun/resource_taikun_cloud_credential_azure.go
  taikun/resource_taikun_cloud_credential_common.go
  taikun/resource_taikun_cloud_credential_openstack.go
  taikun/resource_taikun_policy_profile.go
  taikun/resource_taikun_policy_profile_test.go
  taikun/resource_taikun_project.go
  taikun/resource_taikun_project_test.go
  taikun/resource_taikun_showback_rule.go
  taikun/sweeper_test.go
  taikun/test_helper.go
  templates/data-sources/policy_profile.md.tmpl
  templates/data-sources/policy_profiles.md.tmpl
  templates/resources/policy_profile.md.tmpl
Labels: feat

#161 test(sweepers): set api host
  taikun/sweeper_test.go
Labels: bug, test
