Repository itera-io/terraform-provider-taikun, pull requests merged in 2022-01, with the labels that each got.

#180 chore(sweepers): add different prefixes for taikun's tf and cli tests
  taikun/helper.go
  taikun/resource_taikun_access_profile_test.go
  taikun/resource_taikun_alerting_profile_test.go
  taikun/resource_taikun_backup_credential_test.go
  taikun/resource_taikun_billing_credential_test.go
  taikun/resource_taikun_billing_rule_test.go
  taikun/resource_taikun_cloud_credential_aws_test.go
  taikun/resource_taikun_cloud_credential_azure_test.go
  taikun/resource_taikun_cloud_credential_openstack_test.go
  taikun/resource_taikun_kubeconfig_test.go
  taikun/resource_taikun_kubernetes_profile_test.go
  taikun/resource_taikun_organization_test.go
  taikun/resource_taikun_policy_profile_test.go
  taikun/resource_taikun_project_test.go
  taikun/resource_taikun_showback_credential_test.go
  taikun/resource_taikun_showback_rule_test.go
  taikun/resource_taikun_slack_configuration_test.go
  taikun/resource_taikun_user_test.go
Labels: sweeper

#178 feat: standalone profiles
  .github/workflows/sweep.yml
  docs/data-sources/standalone_profile.md
  docs/data-sources/standalone_profiles.md
  docs/resources/standalone_profile.md
  examples/data-sources/taikun_standalone_profile/data-source.tf
  examples/data-sources/taikun_standalone_profiles/data-source.tf
  examples/resources/taikun_standalone_profile/import.sh
  examples/resources/taikun_standalone_profile/resource.tf
  go.mod
  go.sum
  taikun/data_source_taikun_standalone_profile.go
  taikun/data_source_taikun_standalone_profile_test.go
  taikun/data_source_taikun_standalone_profiles.go
  taikun/data_source_taikun_standalone_profiles_test.go
  taikun/helper.go
  taikun/provider.go
  taikun/resource_taikun_standalone_profile.go
  taikun/resource_taikun_standalone_profile_test.go
  templates/data-sources/standalone_profile.md.tmpl
  templates/data-sources/standalone_profiles.md.tmpl
  templates/resources/standalone_profile.md.tmpl
Labels: feat

#181 refactor: reorder map elements
  taikun/data_source_taikun_access_profiles.go
  taikun/data_source_taikun_alerting_profiles.go
  taikun/data_source_taikun_backup_credentials.go
  taikun/data_source_taikun_billing_credentials.go
  taikun/data_source_taikun_cloud_credentials_aws.go
  taikun/data_source_taikun_cloud_credentials_azure.go
  taikun/data_source_taikun_cloud_credentials_openstack.go
  taikun/data_source_taikun_flavors.go
  taikun/data_source_taikun_kubeconfigs.go
  taikun/data_source_taikun_kubernetes_profiles.go
  taikun/provider.go
  taikun/resource_taikun_access_profile.go
  taikun/resource_taikun_alerting_profile.go
  taikun/resource_taikun_backup_credential.go
  taikun/resource_taikun_billing_credential.go
  taikun/resource_taikun_billing_rule.go
  taikun/resource_taikun_cloud_credential_aws.go
  taikun/resource_taikun_cloud_credential_azure.go
  taikun/resource_taikun_cloud_credential_openstack.go
  taikun/resource_taikun_kubernetes_profile.go
  taikun/resource_taikun_organization.go
  taikun/resource_taikun_policy_profile.go
  taikun/resource_taikun_project.go
  taikun/resource_taikun_project_user_attachment.go
  taikun/resource_taikun_showback_credential.go
  taikun/resource_taikun_showback_rule.go
  taikun/resource_taikun_user.go
Labels: refactor

#179 feat: images data source
  docs/data-sources/images.md
  examples/data-sources/taikun_images/data-source.tf
  taikun/data_source_taikun_images.go
  taikun/data_source_taikun_images_test.go
  taikun/data_source_taikun_kubeconfigs.go
  taikun/data_source_taikun_projects.go
  taikun/provider.go
  taikun/resource_taikun_kubeconfig.go
  templates/data-sources/images.md.tmpl
Labels: feat

#185 refactor: use sets
  docs/data-sources/billing_rule.md
  docs/data-sources/billing_rules.md
  docs/data-sources/policy_profile.md
  docs/data-sources/policy_profiles.md
  docs/data-sources/project.md
  docs/data-sources/projects.md
  docs/data-sources/showback_rule.md
  docs/data-sources/showback_rules.md
  docs/resources/billing_rule.md
  docs/resources/policy_profile.md
  docs/resources/project.md
  docs/resources/showback_rule.md
  taikun/resource_taikun_billing_rule.go
  taikun/resource_taikun_policy_profile.go
  taikun/resource_taikun_project.go
  taikun/resource_taikun_showback_rule.go
Labels: refactor

#186 test: use valid email domain
  taikun/data_source_taikun_organization_test.go
  taikun/helper.go
  taikun/resource_taikun_organization_test.go
Labels: test

#187 feat(kubeconfig): add 'content' attribute
  docs/data-sources/kubeconfig.md
  docs/data-sources/kubeconfigs.md
  docs/resources/kubeconfig.md
  examples/resources/taikun_kubeconfig/resource.tf
  taikun/data_source_taikun_kubeconfigs.go
  taikun/resource_taikun_kubeconfig.go
  taikun/resource_taikun_project_test.go
Labels: feat

#183 feat(projects): standalone vms
  .github/workflows/test.yml
  docs/data-sources/project.md
  docs/data-sources/projects.md
  docs/resources/project.md
  examples/resources/taikun_project/resource.tf
  go.mod
  go.sum
  taikun/data_source_taikun_flavors.go
  taikun/data_source_taikun_images.go
  taikun/data_source_taikun_images_test.go
  taikun/data_source_taikun_projects.go
  taikun/resource_taikun_project.go
  taikun/resource_taikun_project_k8s.go
  taikun/resource_taikun_project_k8s_test.go
  taikun/resource_taikun_project_standalone.go
  taikun/resource_taikun_project_standalone_test.go
  taikun/resource_taikun_project_test.go
  taikun/set.go
  templates/resources/project.md.tmpl
Labels: feat
